spring:
  application:
    name: resilientshop-shopping-api
  #PostgreSQL
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}


server:
  port: ${SERVER_PORT:0}
  error:
    include-stacktrace: never

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    fetchRegistry: true
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://${EUREKA_SERVICE_NAME:localhost}:8761/eureka

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
        permittedNumberOfCallsInHalfOpenState: 4
        minimumNumberOfCalls: 10
        waitDurationInOpenState: 5s
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 5s
        failureRateThreshold: 5
    instances:
      cadastrarFallbackMethod:
        baseConfig: default
      consultarPorIdFallbackMethod:
        baseConfig: default
      listarPorUsuarioFallbackMethod:
        baseConfig: default
