eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka

server:
  port: 8763
  error:
    include-stacktrace: never

spring:
  application:
    name: resilientshop-api-gateway
  cloud:
    gateway:
      routes:
        - id: resilientshop-shopping-api
          uri: lb://resilientshop-shopping-api
          predicates:
            - Path=/pedidos/**
        - id: resilientshop-user-api
          uri: lb://resilientshop-user-api
          predicates:
            - Path=/usuarios/**
        - id: resilientshop-products-api
          uri: lb://resilientshop-products-api
          predicates:
            - Path=/produtos/**
