spring:
  application:
    name: resilientshop-eureka-server

server:
  port: ${SERVER_PORT:8761}
  error:
    include-stacktrace: never

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    eviction-interval-timer-in-ms: 5000
