spring:
  application:
    name: resilientshop-shopping-api
  #PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/resilientshop-shopping
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop

server:
  port: 0
  error:
    include-stacktrace: never

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    fetchRegistry: true
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
        permittedNumberOfCallsInHalfOpenState: 4
        minimumNumberOfCalls: 10
        waitDurationInOpenState: 5s
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 5s
        failureRateThreshold: 5
    instances:
      cadastrarFallbackMethod:
        baseConfig: default
      consultarPorIdFallbackMethod:
        baseConfig: default
      listarPorUsuarioFallbackMethod:
        baseConfig: default
