spring:
  application:
    name: resilientshop-eureka-server

server:
  port: ${SERVER_PORT:8761}
  error:
    include-stacktrace: never

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
  server:
    eviction-interval-timer-in-ms: 5000
