eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    instance-info-replication-interval-seconds: 5
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka

server:
  port: 8763
  error:
    include-stacktrace: never

spring:
  main:
    web-application-type: REACTIVE
  application:
    name: resilientshop-api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
      routes:
        - id: resilientshop-authentication-api
          uri: lb://resilientshop-authentication-api
          predicates:
            - Path=/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: fallback
                fallbackUri: "forward:/fallback/autentica\u00e7\u00e3o"
        - id: resilientshop-shopping-api
          uri: lb://resilientshop-shopping-api
          predicates:
            - Path=/pedidos/**
          filters:
            - name: CircuitBreaker
              args:
                name: fallback
                fallbackUri: forward:/fallback/pedidos
        - id: resilientshop-user-api
          uri: lb://resilientshop-user-api
          predicates:
            - Path=/usuarios/**, /enderecos/**
          filters:
            - name: CircuitBreaker
              args:
                name: fallback
                fallbackUri: "forward:/fallback/usu\u00E1rios"
        - id: resilientshop-products-api
          uri: lb://resilientshop-products-api
          predicates:
            - Path=/produtos/**, /subcategorias/**, /categorias/**
          filters:
            - name: CircuitBreaker
              args:
                name: fallback
                fallbackUri: forward:/fallback/produtos

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 15
        slidingWindowType: COUNT_BASED
        permittedNumberOfCallsInHalfOpenState: 4
        minimumNumberOfCalls: 15
        waitDurationInOpenState: 5s
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 10s
        failureRateThreshold: 10
    instances:
      fallback:
        baseConfig: default
