server:
  port: ${SERVER_PORT:8763}
  error:
    include-stacktrace: never

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    metadata-map:
      "prometheus.scrape": "true"
      "prometheus.path": "/actuator/prometheus"
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://${EUREKA_SERVICE_NAME:localhost}:8761/eureka

spring:
  application:
    name: resilientshop-api-gateway
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.reactive.ReativoSecurityAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.security.reactive.ReativoManagementWebSecurityAutoConfiguration
  main:
    web-application-type: REACTIVE
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
      routes:
        - id: resilientshop-authentication-api
          uri: lb://resilientshop-authentication-api
          predicates:
            - Path=/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: fallback
                fallbackUri: "forward:/fallback/autentica\u00e7\u00e3o"
        - id: resilientshop-shopping-api
          uri: lb://resilientshop-shopping-api
          predicates:
            - Path=/pedidos/**
          filters:
            - name: CircuitBreaker
              args:
                name: fallback
                fallbackUri: forward:/fallback/pedidos
        - id: resilientshop-user-api
          uri: lb://resilientshop-user-api
          predicates:
            - Path=/usuarios/**, /enderecos/**
          filters:
            - name: CircuitBreaker
              args:
                name: fallback
                fallbackUri: "forward:/fallback/usu\u00E1rios"
        - id: resilientshop-products-api
          uri: lb://resilientshop-products-api
          predicates:
            - Path=/produtos/**, /subcategorias/**, /categorias/**
          filters:
            - name: CircuitBreaker
              args:
                name: fallback
                fallbackUri: forward:/fallback/produtos

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 15
        slidingWindowType: COUNT_BASED
        permittedNumberOfCallsInHalfOpenState: 4
        minimumNumberOfCalls: 15
        waitDurationInOpenState: 5s
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 10s
        failureRateThreshold: 10
    instances:
      fallback:
        baseConfig: default
  timelimiter:
    configs:
      default:
        timeoutDuration: 10s
    instances:
      fallback:
        baseConfig: default

management:
  endpoints:
    web:
      exposure:
        include: "*"
