spring:
  application:
    name: resilientshop-discounts-api
  # H2
  datasource:
    url: jdbc:h2:mem:resilientshop-user-test
    username: sa
    password: sa

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${EUREKA_SERVICE_NAME:localhost}:8761/eureka
